#ifndef CML_ERROR_CODES_H
#define CML_ERROR_CODES_H

// Error codes
#define CM_SUCCESS 0
#define CM_MEMORY_ALLOCATION_ERROR -1
#define CM_INVALID_ARGUMENT -2
#define CM_OPERATION_FAILED -3
#define CM_NOT_IMPLEMENTED -4
#define CM_INVALID_STATE -5

#endif // CML_ERROR_CODES_H
