#define _GNU_SOURCE
#include "core/viz_server.h"
#include "core/logging.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>

#ifdef _WIN32
#include <winsock2.h>
#include <ws2tcpip.h>
#include <process.h>
#pragma comment(lib, "ws2_32.lib")
typedef SOCKET socket_t;
#define CLOSE_SOCKET closesocket
#define SOCK_ERR WSAGetLastError()
#else
#include <sys/socket.h>
#include <netinet/in.h>
#include <unistd.h>
#include <pthread.h>
#include <fcntl.h>
typedef int socket_t;
#define CLOSE_SOCKET close
#define INVALID_SOCKET -1
#define SOCKET_ERROR -1
#define SOCK_ERR 0
#endif

// Placeholder for embedded assets (would be generated by a script)
static const char* HTML_CONTENT =
    "<!DOCTYPE html><html><head><title>C-ML Viz</title></head>"
    "<body><h1>C-ML Visualization</h1><p>Waiting for data...</p>"
    "<script>"
    "const evtSource = new EventSource('/events');"
    "evtSource.onmessage = function(event) {"
    "  const data = JSON.parse(event.data);"
    "  console.log('Update:', data);"
    "  document.body.innerHTML += '<pre>' + JSON.stringify(data, null, 2) + '</pre>';"
    "};"
    "</script></body></html>";

#define PORT 8001
#define MAX_CLIENTS 5
#define BUFFER_SIZE 4096

static volatile bool g_server_running = false;
static socket_t g_server_socket       = INVALID_SOCKET;
static socket_t g_clients[MAX_CLIENTS];

#ifdef _WIN32
static HANDLE g_server_thread;
#else
static pthread_t g_server_thread;
#endif

// Initialize clients array
static void init_clients(void) {
    for (int i = 0; i < MAX_CLIENTS; i++) {
        g_clients[i] = INVALID_SOCKET;
    }
}

// Add a client
static void add_client(socket_t client) {
    for (int i = 0; i < MAX_CLIENTS; i++) {
        if (g_clients[i] == INVALID_SOCKET) {
            g_clients[i] = client;
            return;
        }
    }
    // Full, reject
    CLOSE_SOCKET(client);
}

// Remove a client
static void remove_client(int index) {
    if (index >= 0 && index < MAX_CLIENTS) {
        if (g_clients[index] != INVALID_SOCKET) {
            CLOSE_SOCKET(g_clients[index]);
            g_clients[index] = INVALID_SOCKET;
        }
    }
}

// Send SSE event to all clients
void viz_server_broadcast(const char* event_type, const char* json_data) {
    if (!g_server_running)
        return;

    char buffer[BUFFER_SIZE];
    int len = snprintf(buffer, sizeof(buffer),
                       "event: %s\n"
                       "data: %s\n\n",
                       event_type, json_data);

    for (int i = 0; i < MAX_CLIENTS; i++) {
        if (g_clients[i] != INVALID_SOCKET) {
            int sent = send(g_clients[i], buffer, len, 0);
            if (sent < 0) {
                remove_client(i);
            }
        }
    }
}

// Handle individual client request
static void handle_request(socket_t client) {
    char buffer[BUFFER_SIZE];
    int received = recv(client, buffer, sizeof(buffer) - 1, 0);
    if (received <= 0) {
        CLOSE_SOCKET(client);
        return;
    }
    buffer[received] = '\0';

    // Simple parsing
    if (strncmp(buffer, "GET /events", 11) == 0) {
        // SSE Stream
        const char* headers = "HTTP/1.1 200 OK\r\n"
                              "Content-Type: text/event-stream\r\n"
                              "Cache-Control: no-cache\r\n"
                              "Connection: keep-alive\r\n"
                              "Access-Control-Allow-Origin: *\r\n\r\n";
        send(client, headers, strlen(headers), 0);
        add_client(client); // Keep connection open
    } else if (strncmp(buffer, "GET / ", 6) == 0 || strncmp(buffer, "GET /index.html", 15) == 0) {
        // Serve HTML
        char headers[512];
        snprintf(headers, sizeof(headers),
                 "HTTP/1.1 200 OK\r\n"
                 "Content-Type: text/html\r\n"
                 "Content-Length: %zu\r\n"
                 "Connection: close\r\n\r\n",
                 strlen(HTML_CONTENT));
        send(client, headers, strlen(headers), 0);
        send(client, HTML_CONTENT, strlen(HTML_CONTENT), 0);
        CLOSE_SOCKET(client);
    } else {
        // 404
        const char* resp = "HTTP/1.1 404 Not Found\r\nContent-Length: 0\r\n\r\n";
        send(client, resp, strlen(resp), 0);
        CLOSE_SOCKET(client);
    }
}

// Server loop
#ifdef _WIN32
unsigned __stdcall server_loop(void* arg) {
#else
void* server_loop(void* arg) {
#endif
    (void)arg;
    struct sockaddr_in address;
    int addrlen = sizeof(address);

    address.sin_family      = AF_INET;
    address.sin_addr.s_addr = INADDR_ANY;
    address.sin_port        = htons(PORT);

    if (bind(g_server_socket, (struct sockaddr*)&address, sizeof(address)) < 0) {
        LOG_ERROR("Viz Server: Bind failed");
        return 0;
    }

    if (listen(g_server_socket, 3) < 0) {
        LOG_ERROR("Viz Server: Listen failed");
        return 0;
    }

    LOG_INFO("Viz Server listening on http://localhost:%d", PORT);

    while (g_server_running) {
        socket_t new_socket;
        struct sockaddr_in client_addr;
#ifdef _WIN32
        int client_len = sizeof(client_addr);
#else
        socklen_t client_len = sizeof(client_addr);
#endif

        new_socket = accept(g_server_socket, (struct sockaddr*)&client_addr, &client_len);
        if (new_socket == INVALID_SOCKET) {
            if (g_server_running)
                LOG_ERROR("Viz Server: Accept failed");
            continue;
        }

        handle_request(new_socket);
    }
    return 0;
}

int viz_server_init(void) {
#ifdef _WIN32
    WSADATA wsaData;
    if (WSAStartup(MAKEWORD(2, 2), &wsaData) != 0)
        return -1;
#endif

    init_clients();

    g_server_socket = socket(AF_INET, SOCK_STREAM, 0);
    if (g_server_socket == INVALID_SOCKET)
        return -1;

    // Allow address reuse
    int opt = 1;
    setsockopt(g_server_socket, SOL_SOCKET, SO_REUSEADDR, (const char*)&opt, sizeof(opt));

    g_server_running = true;

#ifdef _WIN32
    g_server_thread = (HANDLE)_beginthreadex(NULL, 0, server_loop, NULL, 0, NULL);
#else
    if (pthread_create(&g_server_thread, NULL, server_loop, NULL) != 0) {
        return -1;
    }
    pthread_detach(g_server_thread);
#endif

    return 0;
}

void viz_server_shutdown(void) {
    g_server_running = false;
    if (g_server_socket != INVALID_SOCKET) {
        CLOSE_SOCKET(g_server_socket);
        g_server_socket = INVALID_SOCKET;
    }

    for (int i = 0; i < MAX_CLIENTS; i++) {
        remove_client(i);
    }

#ifdef _WIN32
    WSACleanup();
#endif
}
