@echo off
REM C-ML Development Environment Setup Script (Batch)
REM Installs MLIR, CUDA, Vulkan, SLEEF, and other dependencies for Windows
REM This file is generated by AI, so it may not be perfect.

echo.
echo ========================================
echo C-ML Development Environment Setup
echo ========================================
echo.

REM Check for administrator privileges
net session >nul 2>&1
if %errorLevel% neq 0 (
    echo ERROR: This script requires administrator privileges.
    echo Please run as Administrator.
    pause
    exit /b 1
)

REM Check for Chocolatey
where choco >nul 2>&1
if %errorLevel% neq 0 (
    echo Installing Chocolatey package manager...
    powershell -NoProfile -ExecutionPolicy Bypass -Command "Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))"
    if %errorLevel% neq 0 (
        echo ERROR: Failed to install Chocolatey
        pause
        exit /b 1
    )
    echo Chocolatey installed successfully.
    echo.
)

echo What would you like to install?
echo 1. Everything (recommended)
echo 2. MLIR only (required)
echo 3. MLIR + CUDA
echo 4. MLIR + Vulkan
echo 5. Build tools only
echo.
set /p choice="Enter choice [1-5]: "

if "%choice%"=="1" goto install_all
if "%choice%"=="2" goto install_mlir
if "%choice%"=="3" goto install_mlir_cuda
if "%choice%"=="4" goto install_mlir_vulkan
if "%choice%"=="5" goto install_build_tools
goto invalid_choice

:install_all
echo.
echo Installing all components...
call :install_build_tools
call :install_mlir
call :install_cuda
call :install_vulkan
goto end

:install_mlir
echo.
echo Installing MLIR...
call :install_build_tools
call :install_mlir_impl
goto end

:install_mlir_cuda
echo.
echo Installing MLIR + CUDA...
call :install_build_tools
call :install_mlir_impl
call :install_cuda
goto end

:install_mlir_vulkan
echo.
echo Installing MLIR + Vulkan...
call :install_build_tools
call :install_mlir_impl
call :install_vulkan
goto end

:install_build_tools
echo.
echo Installing build tools...
choco install cmake git python3 ninja -y
if %errorLevel% neq 0 (
    echo ERROR: Failed to install build tools
    pause
    exit /b 1
)
echo Build tools installed successfully.
goto :eof

:install_mlir_impl
echo.
echo Installing LLVM/MLIR...
choco install llvm -y
if %errorLevel% neq 0 (
    echo ERROR: Failed to install LLVM
    pause
    exit /b 1
)
echo.
echo MLIR installed successfully.
echo.
echo IMPORTANT: Add these to your environment variables:
echo   LLVM_DIR=C:\Program Files\LLVM\lib\cmake\llvm
echo   MLIR_DIR=C:\Program Files\LLVM\lib\cmake\mlir
echo   Add C:\Program Files\LLVM\bin to PATH
goto :eof

:install_cuda
echo.
echo Checking for NVIDIA GPU...
wmic path win32_VideoController get name | findstr /i "NVIDIA" >nul
if %errorLevel% neq 0 (
    echo No NVIDIA GPU detected. Skipping CUDA installation.
    goto :eof
)
echo NVIDIA GPU detected. Installing CUDA...
choco install cuda -y
if %errorLevel% neq 0 (
    echo ERROR: Failed to install CUDA
    pause
    exit /b 1
)
echo.
echo CUDA installed successfully.
echo.
echo IMPORTANT: Add CUDA to your PATH:
echo   Add C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.x\bin to PATH
goto :eof

:install_vulkan
echo.
echo Installing Vulkan SDK...
choco install vulkan-sdk -y
if %errorLevel% neq 0 (
    echo ERROR: Failed to install Vulkan SDK
    pause
    exit /b 1
)
echo.
echo Vulkan SDK installed successfully.
echo.
echo IMPORTANT: Set environment variable:
echo   VULKAN_SDK=C:\VulkanSDK\<version>
echo   Add %%VULKAN_SDK%%\Bin to PATH
goto :eof

:invalid_choice
echo.
echo Invalid choice. Please run the script again.
pause
exit /b 1

:end
echo.
echo ========================================
echo Installation Complete!
echo ========================================
echo.
echo Next steps:
echo   1. Set environment variables as shown above
echo   2. Restart your terminal/command prompt
echo   3. Build C-ML: cd C-ML ^&^& mkdir build ^&^& cd build
echo   4. Configure: cmake .. -DMLIR_DIR=%%MLIR_DIR%%
echo   5. Build: cmake --build . --config Release
echo.
pause
