#!/bin/bash
# C-ML Development Environment Setup Script
# Installs MLIR, CUDA, Vulkan, SLEEF, and other dependencies
# Supports: Linux (Ubuntu/Debian, Arch, Fedora), macOS, Windows (WSL2)
# This file is generated by AI, so it may not be perfect.

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Detect OS
detect_os() {
    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        if [ -f /etc/debian_version ]; then
            OS="ubuntu"
            OS_FAMILY="debian"
        elif [ -f /etc/arch-release ]; then
            OS="arch"
            OS_FAMILY="arch"
        elif [ -f /etc/fedora-release ] || [ -f /etc/redhat-release ]; then
            OS="fedora"
            OS_FAMILY="rhel"
        else
            OS="linux"
            OS_FAMILY="linux"
        fi
    elif [[ "$OSTYPE" == "darwin"* ]]; then
        OS="macos"
        OS_FAMILY="macos"
    elif [[ "$OSTYPE" == "msys" ]] || [[ "$OSTYPE" == "cygwin" ]]; then
        OS="windows"
        OS_FAMILY="windows"
    else
        OS="unknown"
        OS_FAMILY="unknown"
    fi
}

# Print functions
print_success() { echo -e "${GREEN}✓${NC} $1"; }
print_error() { echo -e "${RED}✗${NC} $1"; }
print_info() { echo -e "${BLUE}ℹ${NC} $1"; }
print_warning() { echo -e "${YELLOW}⚠${NC} $1"; }
print_header() { echo -e "\n${CYAN}=== $1 ===${NC}\n"; }

# Check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Check if package is installed (Linux)
package_installed() {
    if [ "$OS_FAMILY" = "debian" ]; then
        dpkg -l | grep -q "^ii.*$1" 2>/dev/null
    elif [ "$OS_FAMILY" = "arch" ]; then
        pacman -Qi "$1" >/dev/null 2>&1
    elif [ "$OS_FAMILY" = "rhel" ]; then
        rpm -q "$1" >/dev/null 2>&1
    else
        return 1
    fi
}

# Detect GPU
detect_gpu() {
    GPU_TYPE="none"
    if command_exists nvidia-smi; then
        GPU_TYPE="nvidia"
        print_success "NVIDIA GPU detected"
    elif [ -f /sys/class/drm/card0/device/vendor ] && \
         grep -q "0x1002" /sys/class/drm/card0/device/vendor 2>/dev/null; then
        GPU_TYPE="amd"
        print_success "AMD GPU detected"
    elif [ "$OS" = "macos" ]; then
        GPU_TYPE="apple"
        print_success "Apple GPU detected (Metal support available)"
    else
        print_info "No GPU detected or GPU detection failed"
    fi
}

# Install MLIR/LLVM
install_mlir() {
    print_header "Installing MLIR/LLVM"

    if [ "$OS" = "ubuntu" ]; then
        if ! package_installed "llvm-18-dev"; then
            print_info "Adding LLVM repository..."
            wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
            echo "deb http://apt.llvm.org/$(lsb_release -cs)/ llvm-toolchain-$(lsb_release -cs)-18 main" | sudo tee /etc/apt/sources.list.d/llvm.list
            sudo apt-get update
            # Install MLIR tools (mlir-opt, mlir-translate) and llc
            sudo apt-get install -y llvm-18-dev libmlir-18-dev mlir-18-tools llvm-18-tools clang-18
            print_success "MLIR and LLVM tools installed (mlir-opt, mlir-translate, llc)"
        else
            print_success "MLIR already installed"
        fi

        # Set MLIR_DIR
        if [ -d "/usr/lib/llvm-18/lib/cmake/mlir" ]; then
            export MLIR_DIR="/usr/lib/llvm-18/lib/cmake/mlir"
            export LLVM_DIR="/usr/lib/llvm-18/lib/cmake/llvm"
        fi

    elif [ "$OS" = "arch" ]; then
        if ! package_installed "llvm"; then
            # llvm package includes llc, mlir package includes mlir-opt and mlir-translate
            sudo pacman -S --noconfirm llvm mlir clang
            print_success "MLIR and LLVM tools installed (mlir-opt, mlir-translate, llc)"
        else
            print_success "MLIR already installed"
        fi

        # Set MLIR_DIR
        if [ -d "/usr/lib/cmake/mlir" ]; then
            export MLIR_DIR="/usr/lib/cmake/mlir"
            export LLVM_DIR="/usr/lib/cmake/llvm"
        fi

    elif [ "$OS" = "fedora" ]; then
        if ! package_installed "llvm-devel"; then
            # Install MLIR and LLVM tools (mlir-opt, mlir-translate, llc)
            sudo dnf install -y llvm-devel mlir-devel llvm-tools clang-devel
            print_success "MLIR and LLVM tools installed (mlir-opt, mlir-translate, llc)"
        else
            print_success "MLIR already installed"
        fi

        # Set MLIR_DIR
        if [ -d "/usr/lib64/cmake/mlir" ]; then
            export MLIR_DIR="/usr/lib64/cmake/mlir"
            export LLVM_DIR="/usr/lib64/cmake/llvm"
        fi

    elif [ "$OS" = "macos" ]; then
        if ! command_exists brew; then
            print_error "Homebrew not found. Install from https://brew.sh"
            return 1
        fi

        if ! brew list llvm@18 >/dev/null 2>&1; then
            print_info "Installing LLVM 18 via Homebrew (this may take 30-60 minutes)..."
            brew install llvm@18
            print_success "MLIR installed"
        else
            print_success "MLIR already installed"
        fi

        # Set MLIR_DIR
        LLVM_PREFIX=$(brew --prefix llvm@18)
        export MLIR_DIR="$LLVM_PREFIX/lib/cmake/mlir"
        export LLVM_DIR="$LLVM_PREFIX/lib/cmake/llvm"
        export LDFLAGS="-L$LLVM_PREFIX/lib"
        export CPPFLAGS="-I$LLVM_PREFIX/include"
        export PATH="$LLVM_PREFIX/bin:$PATH"

        print_info "Add these to your ~/.zshrc or ~/.bashrc:"
        echo "export LLVM_DIR=\"$LLVM_PREFIX\""
        echo "export LDFLAGS=\"-L\$LLVM_DIR/lib\""
        echo "export CPPFLAGS=\"-I\$LLVM_DIR/include\""
        echo "export PATH=\"\$LLVM_DIR/bin:\$PATH\""

    else
        print_warning "OS not supported for automatic MLIR installation"
        print_info "Please install MLIR manually. See docs/MLIR_INTEGRATION_PLAN.md"
        return 1
    fi

    # Verify installation
    if [ -n "$MLIR_DIR" ] && [ -d "$MLIR_DIR" ]; then
        print_success "MLIR_DIR set to: $MLIR_DIR"
    else
        print_warning "MLIR_DIR not automatically detected. Set it manually:"
        print_info "export MLIR_DIR=/path/to/mlir/lib/cmake/mlir"
    fi

    # Verify CLI tools are available
    print_info "Verifying MLIR CLI tools..."
    if command_exists mlir-opt; then
        print_success "mlir-opt found: $(which mlir-opt)"
    else
        print_warning "mlir-opt not found in PATH"
    fi

    if command_exists mlir-translate; then
        print_success "mlir-translate found: $(which mlir-translate)"
    else
        print_warning "mlir-translate not found in PATH"
    fi

    if command_exists llc; then
        print_success "llc found: $(which llc)"
    else
        print_warning "llc not found in PATH"
    fi

    if command_exists llvm-as; then
        print_success "llvm-as found: $(which llvm-as)"
    else
        print_info "llvm-as not found (optional, for SPIR-V via LLVM path)"
    fi
}

# Install CUDA
install_cuda() {
    if [ "$GPU_TYPE" != "nvidia" ]; then
        print_info "Skipping CUDA (no NVIDIA GPU detected)"
        return 0
    fi

    print_header "Installing CUDA Toolkit"

    if command_exists nvcc; then
        CUDA_VERSION=$(nvcc --version | grep "release" | sed 's/.*release \([0-9]\+\.[0-9]\+\).*/\1/')
        print_success "CUDA already installed: $CUDA_VERSION"
        return 0
    fi

    if [ "$OS" = "ubuntu" ]; then
        print_info "Installing CUDA Toolkit..."
        print_warning "This will install CUDA 12.x. For other versions, visit: https://developer.nvidia.com/cuda-downloads"

        wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu$(lsb_release -rs | tr -d '.')/x86_64/cuda-keyring_1.1-1_all.deb
        sudo dpkg -i cuda-keyring_1.1-1_all.deb
        sudo apt-get update
        sudo apt-get install -y cuda-toolkit-12-4
        rm -f cuda-keyring_1.1-1_all.deb

        print_success "CUDA installed"
        print_info "Add to your ~/.bashrc:"
        echo "export PATH=/usr/local/cuda/bin:\$PATH"
        echo "export LD_LIBRARY_PATH=/usr/local/cuda/lib64:\$LD_LIBRARY_PATH"

    elif [ "$OS" = "arch" ]; then
        print_info "Installing CUDA via pacman..."
        sudo pacman -S --noconfirm cuda cudnn
        print_success "CUDA installed"

    elif [ "$OS" = "fedora" ]; then
        print_info "Installing CUDA..."
        sudo dnf config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/fedora$(rpm -E %fedora)/x86_64/cuda-fedora$(rpm -E %fedora).repo
        sudo dnf install -y cuda-toolkit
        print_success "CUDA installed"

    elif [ "$OS" = "macos" ]; then
        print_warning "CUDA is not supported on macOS. Use Metal instead."
        return 0

    else
        print_warning "Automatic CUDA installation not supported for this OS"
        print_info "Download from: https://developer.nvidia.com/cuda-downloads"
        return 1
    fi
}

# Install Vulkan SDK
install_vulkan() {
    print_header "Installing Vulkan SDK"

    if command_exists vulkaninfo; then
        VULKAN_VERSION=$(vulkaninfo --summary 2>/dev/null | grep "Vulkan Instance Version" | awk '{print $4}' || echo "unknown")
        print_success "Vulkan SDK already installed: $VULKAN_VERSION"
        return 0
    fi

    if [ "$OS" = "ubuntu" ]; then
        print_info "Installing Vulkan SDK..."
        sudo apt-get install -y vulkan-tools libvulkan-dev vulkan-validationlayers-dev

        # Install LunarG Vulkan SDK for latest features
        VULKAN_VERSION="1.3.280.0"
        VULKAN_SDK_URL="https://packages.lunarg.com/sdk/${VULKAN_VERSION}/linux/vulkan-sdk-${VULKAN_VERSION}-x86_64.tar.gz"

        print_info "Downloading LunarG Vulkan SDK..."
        cd /tmp
        wget -q "$VULKAN_SDK_URL" -O vulkan-sdk.tar.gz
        tar -xzf vulkan-sdk.tar.gz
        sudo mkdir -p /opt/vulkan
        sudo mv vulkan-sdk-${VULKAN_VERSION}/* /opt/vulkan/
        rm -rf vulkan-sdk-${VULKAN_VERSION} vulkan-sdk.tar.gz

        export VULKAN_SDK="/opt/vulkan"
        export PATH="$VULKAN_SDK/bin:$PATH"
        export LD_LIBRARY_PATH="$VULKAN_SDK/lib:$LD_LIBRARY_PATH"
        export VK_LAYER_PATH="$VULKAN_SDK/etc/vulkan/explicit_layer.d"

        print_success "Vulkan SDK installed"
        print_info "Add to your ~/.bashrc:"
        echo "export VULKAN_SDK=/opt/vulkan"
        echo "export PATH=\$VULKAN_SDK/bin:\$PATH"
        echo "export LD_LIBRARY_PATH=\$VULKAN_SDK/lib:\$LD_LIBRARY_PATH"

    elif [ "$OS" = "arch" ]; then
        sudo pacman -S --noconfirm vulkan-devel vulkan-tools vulkan-validation-layers
        print_success "Vulkan SDK installed"

    elif [ "$OS" = "fedora" ]; then
        sudo dnf install -y vulkan-devel vulkan-tools vulkan-validation-layers
        print_success "Vulkan SDK installed"

    elif [ "$OS" = "macos" ]; then
        if ! command_exists brew; then
            print_error "Homebrew required for Vulkan on macOS"
            return 1
        fi

        print_info "Installing Vulkan SDK via Homebrew..."
        brew install vulkan-headers vulkan-loader vulkan-tools
        print_success "Vulkan SDK installed"

    else
        print_warning "Automatic Vulkan installation not supported"
        print_info "Download from: https://vulkan.lunarg.com/sdk/home"
        return 1
    fi
}

# Install SLEEF
install_sleef() {
    print_header "Installing SLEEF"

    if pkg-config --exists sleef 2>/dev/null; then
        SLEEF_VERSION=$(pkg-config --modversion sleef)
        print_success "SLEEF already installed: $SLEEF_VERSION"
        return 0
    fi

    print_info "Building SLEEF from source..."

    # Create local directory
    mkdir -p "$HOME/.local/src"
    cd "$HOME/.local/src"

    if [ ! -d "sleef" ]; then
        print_info "Cloning SLEEF repository..."
        git clone https://github.com/shibatch/sleef.git
    fi

    cd sleef
    git pull

    mkdir -p build
    cd build

    cmake -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX="$HOME/.local" \
          -DSLEEF_ENABLE_LLVM_BITCODE=OFF \
          -DBUILD_SHARED_LIBS=ON \
          ..

    make -j$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo 4)
    make install

    print_success "SLEEF installed to $HOME/.local"

    # Update environment
    export LD_LIBRARY_PATH="$HOME/.local/lib:$LD_LIBRARY_PATH"
    export PKG_CONFIG_PATH="$HOME/.local/lib/pkgconfig:$PKG_CONFIG_PATH"

    print_info "Add to your ~/.bashrc or ~/.zshrc:"
    echo "export LD_LIBRARY_PATH=\"\$HOME/.local/lib:\$LD_LIBRARY_PATH\""
    echo "export PKG_CONFIG_PATH=\"\$HOME/.local/lib/pkgconfig:\$PKG_CONFIG_PATH\""
}

# Install BLAS libraries
install_blas() {
    print_header "Installing BLAS Libraries"

    if [ "$OS" = "ubuntu" ]; then
        if ! package_installed "libopenblas-dev"; then
            print_info "Installing OpenBLAS..."
            sudo apt-get install -y libopenblas-dev
            print_success "OpenBLAS installed"
        else
            print_success "OpenBLAS already installed"
        fi

    elif [ "$OS" = "arch" ]; then
        if ! package_installed "openblas"; then
            sudo pacman -S --noconfirm openblas
            print_success "OpenBLAS installed"
        else
            print_success "OpenBLAS already installed"
        fi

    elif [ "$OS" = "fedora" ]; then
        if ! package_installed "openblas-devel"; then
            sudo dnf install -y openblas-devel
            print_success "OpenBLAS installed"
        else
            print_success "OpenBLAS already installed"
        fi

    elif [ "$OS" = "macos" ]; then
        if ! brew list openblas >/dev/null 2>&1; then
            brew install openblas
            print_success "OpenBLAS installed"
        else
            print_success "OpenBLAS already installed"
        fi

    else
        print_warning "Automatic BLAS installation not supported"
    fi
}

# Install ROCm (AMD GPU support)
install_rocm() {
    if [ "$GPU_TYPE" != "amd" ] || [ "$OS" != "ubuntu" ]; then
        print_info "Skipping ROCm (AMD GPU on Ubuntu required)"
        return 0
    fi

    print_header "Installing ROCm"

    if command_exists rocminfo; then
        print_success "ROCm already installed"
        return 0
    fi

    print_info "Installing ROCm (this may take a while)..."
    print_warning "ROCm installation requires specific kernel versions. See: https://rocm.docs.amd.com/"

    wget -qO - https://repo.radeon.com/rocm/rocm.gpg.key | sudo apt-key add -
    echo 'deb [arch=amd64] https://repo.radeon.com/rocm/apt/6.0/ ubuntu main' | sudo tee /etc/apt/sources.list.d/rocm.list
    sudo apt-get update
    sudo apt-get install -y rocm-dev

    print_success "ROCm installed"
    print_info "Add to your ~/.bashrc:"
    echo "export PATH=/opt/rocm/bin:\$PATH"
    echo "export LD_LIBRARY_PATH=/opt/rocm/lib:\$LD_LIBRARY_PATH"
}

# Install SPIRV-Tools (spirv-as)
install_spirv_tools() {
    print_header "Installing SPIRV-Tools (spirv-as)"

    if command_exists spirv-as; then
        print_success "spirv-as already installed"
        return 0
    fi

    if [ "$OS" = "ubuntu" ]; then
        sudo apt-get install -y spirv-tools
        print_success "SPIRV-Tools installed"
    elif [ "$OS" = "arch" ]; then
        sudo pacman -S --noconfirm spirv-tools
        print_success "SPIRV-Tools installed"
    elif [ "$OS" = "fedora" ]; then
        sudo dnf install -y spirv-tools
        print_success "SPIRV-Tools installed"
    elif [ "$OS" = "macos" ]; then
        if ! command_exists brew; then
            print_error "Homebrew required"
            return 1
        fi
        brew install spirv-tools
        print_success "SPIRV-Tools installed"
    else
        print_warning "Automatic SPIRV-Tools installation not supported"
        print_info "Build from source: https://github.com/KhronosGroup/SPIRV-Tools"
        return 1
    fi
}

# Install SPIRV-Cross (for Metal codegen)
install_spirv_cross() {
    print_header "Installing SPIRV-Cross"

    if command_exists spirv-cross; then
        print_success "spirv-cross already installed"
        return 0
    fi

    if [ "$OS" = "ubuntu" ]; then
        # Try package manager first
        if sudo apt-get install -y spirv-cross 2>/dev/null; then
            print_success "SPIRV-Cross installed via apt"
        else
            print_warning "spirv-cross not in apt repositories"
            print_info "Build from source: https://github.com/KhronosGroup/SPIRV-Cross"
        fi
    elif [ "$OS" = "arch" ]; then
        # Check AUR
        if command_exists yay; then
            yay -S spirv-cross-git
            print_success "SPIRV-Cross installed via AUR"
        else
            print_warning "yay not found. Install yay or build from source"
            print_info "Build from source: https://github.com/KhronosGroup/SPIRV-Cross"
        fi
    elif [ "$OS" = "fedora" ]; then
        print_warning "spirv-cross may not be in Fedora repos"
        print_info "Build from source: https://github.com/KhronosGroup/SPIRV-Cross"
    elif [ "$OS" = "macos" ]; then
        if ! command_exists brew; then
            print_error "Homebrew required"
            return 1
        fi
        brew install spirv-cross
        print_success "SPIRV-Cross installed"
    else
        print_warning "Automatic SPIRV-Cross installation not supported"
        print_info "Build from source: https://github.com/KhronosGroup/SPIRV-Cross"
        return 1
    fi
}

# Install llvm-spirv (LLVM to SPIR-V translator)
install_llvm_spirv() {
    print_header "Installing llvm-spirv"

    if command_exists llvm-spirv; then
        print_success "llvm-spirv already installed"
        return 0
    fi

    print_info "llvm-spirv is optional and may need to be built from source"
    print_info "It's used for SPIR-V generation via LLVM IR path (fallback)"

    if [ "$OS" = "ubuntu" ]; then
        # Try package manager
        if sudo apt-get install -y llvm-spirv 2>/dev/null; then
            print_success "llvm-spirv installed"
        else
            print_warning "llvm-spirv not in repositories"
            print_info "Build from source: https://github.com/KhronosGroup/SPIRV-LLVM-Translator"
        fi
    elif [ "$OS" = "arch" ]; then
        if command_exists yay; then
            yay -S llvm-spirv-git
            print_success "llvm-spirv installed via AUR"
        else
            print_warning "yay not found. Build from source"
            print_info "Build from source: https://github.com/KhronosGroup/SPIRV-LLVM-Translator"
        fi
    else
        print_info "Build from source: https://github.com/KhronosGroup/SPIRV-LLVM-Translator"
        print_info "This is optional - C-ML has fallback mechanisms"
    fi
}

# Install Naga (WGSL converter)
install_naga() {
    print_header "Installing Naga (WGSL converter)"

    if command_exists naga; then
        print_success "naga already installed"
        return 0
    fi

    print_info "Naga is a Rust tool for converting SPIR-V to WGSL"

    if ! command_exists cargo; then
        print_info "Installing Rust and Cargo..."
        if command_exists curl; then
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            source "$HOME/.cargo/env"
            print_success "Rust installed"
        else
            print_error "curl not found. Install Rust manually from https://rustup.rs/"
            return 1
        fi
    fi

    print_info "Installing naga via Cargo..."
    cargo install naga-cli

    if command_exists naga; then
        print_success "Naga installed"
        print_info "Add to your ~/.bashrc or ~/.zshrc:"
        echo "export PATH=\"\$HOME/.cargo/bin:\$PATH\""
    else
        print_warning "Naga installation may have failed"
        print_info "Try manually: cargo install naga-cli"
    fi
}

# Install additional codegen tools
install_codegen_tools() {
    print_header "Installing Additional Codegen Tools"

    install_spirv_tools
    install_spirv_cross
    install_llvm_spirv

    # Ask about naga (requires Rust)
    echo ""
    read -p "Install Naga (WGSL converter, requires Rust)? [y/N]: " install_naga_choice
    if [ "$install_naga_choice" = "y" ] || [ "$install_naga_choice" = "Y" ]; then
        install_naga
    else
        print_info "Skipping Naga installation"
    fi
}

# Install build tools
install_build_tools() {
    print_header "Installing Build Tools"

    if [ "$OS" = "ubuntu" ]; then
        sudo apt-get update
        # build-essential includes gcc, g++, make
        sudo apt-get install -y build-essential cmake ninja-build git pkg-config python3 python3-pip nodejs npm
        print_success "Build tools installed (gcc, make, cmake, npm, python3)"

    elif [ "$OS" = "arch" ]; then
        # base-devel includes gcc, make
        sudo pacman -S --noconfirm base-devel cmake ninja git pkg-config python python-pip nodejs npm
        print_success "Build tools installed (gcc, make, cmake, npm, python)"

    elif [ "$OS" = "fedora" ]; then
        sudo dnf install -y gcc gcc-c++ make cmake ninja-build git pkgconfig python3 python3-pip nodejs npm
        print_success "Build tools installed (gcc, make, cmake, npm, python3)"

    elif [ "$OS" = "macos" ]; then
        if ! command_exists xcode-select; then
            print_error "Xcode Command Line Tools not found"
            print_info "Run: xcode-select --install"
            return 1
        fi

        if ! command_exists brew; then
            print_error "Homebrew not found. Install from https://brew.sh"
            return 1
        fi

        # Xcode Command Line Tools includes gcc (via clang), make
        brew install cmake ninja git pkg-config python3 node
        print_success "Build tools installed (gcc/clang, make, cmake, npm, python3)"

    else
        print_warning "Automatic build tools installation not supported"
    fi

    # Verify installations
    print_info "Verifying build tools..."
    if command_exists gcc; then
        GCC_VERSION=$(gcc --version | head -n1)
        print_success "gcc found: $GCC_VERSION"
    elif command_exists clang; then
        CLANG_VERSION=$(clang --version | head -n1)
        print_success "clang found: $CLANG_VERSION (using as C compiler)"
    else
        print_warning "No C compiler found (gcc or clang)"
    fi

    if command_exists make; then
        MAKE_VERSION=$(make --version | head -n1)
        print_success "make found: $MAKE_VERSION"
    else
        print_warning "make not found"
    fi

    if command_exists cmake; then
        CMAKE_VERSION=$(cmake --version | head -n1)
        print_success "cmake found: $CMAKE_VERSION"
    else
        print_warning "cmake not found"
    fi

    if command_exists npm; then
        NPM_VERSION=$(npm --version)
        NODE_VERSION=$(node --version 2>/dev/null || echo "unknown")
        print_success "npm found: v$NPM_VERSION (Node.js $NODE_VERSION)"
    else
        print_warning "npm not found"
    fi

    if command_exists python3; then
        PYTHON_VERSION=$(python3 --version)
        print_success "python3 found: $PYTHON_VERSION"
    elif command_exists python; then
        PYTHON_VERSION=$(python --version)
        print_success "python found: $PYTHON_VERSION"
    else
        print_warning "python not found"
    fi
}

# Install Node.js and npm (if not already installed)
install_nodejs() {
    print_header "Installing Node.js and npm"

    if command_exists npm && command_exists node; then
        NODE_VERSION=$(node --version)
        NPM_VERSION=$(npm --version)
        print_success "Node.js already installed: $NODE_VERSION (npm v$NPM_VERSION)"
        return 0
    fi

    if [ "$OS" = "ubuntu" ]; then
        # Install Node.js 18.x LTS
        curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
        sudo apt-get install -y nodejs
        print_success "Node.js and npm installed"

    elif [ "$OS" = "arch" ]; then
        sudo pacman -S --noconfirm nodejs npm
        print_success "Node.js and npm installed"

    elif [ "$OS" = "fedora" ]; then
        sudo dnf install -y nodejs npm
        print_success "Node.js and npm installed"

    elif [ "$OS" = "macos" ]; then
        if ! command_exists brew; then
            print_error "Homebrew required"
            return 1
        fi
        brew install node
        print_success "Node.js and npm installed"

    else
        print_warning "Automatic Node.js installation not supported"
        print_info "Download from: https://nodejs.org/"
        return 1
    fi

    # Verify installation
    if command_exists npm; then
        NPM_VERSION=$(npm --version)
        NODE_VERSION=$(node --version)
        print_success "Node.js $NODE_VERSION and npm v$NPM_VERSION installed"
    fi
}

# Install React and frontend dependencies (for viz-ui)
install_frontend_deps() {
    print_header "Installing Frontend Dependencies"

    if ! command_exists npm; then
        print_error "npm not found. Install Node.js first."
        return 1
    fi

    # Check if viz-ui directory exists
    if [ ! -d "viz-ui" ] && [ ! -d "../viz-ui" ]; then
        print_warning "viz-ui directory not found. Skipping frontend dependencies."
        return 0
    fi

    # Determine viz-ui path
    VIZ_UI_PATH="viz-ui"
    if [ ! -d "$VIZ_UI_PATH" ]; then
        VIZ_UI_PATH="../viz-ui"
    fi

    if [ ! -d "$VIZ_UI_PATH" ]; then
        print_warning "viz-ui directory not found at $VIZ_UI_PATH"
        return 0
    fi

    print_info "Installing npm dependencies in $VIZ_UI_PATH..."
    cd "$VIZ_UI_PATH"

    if [ -f "package.json" ]; then
        npm install
        if [ $? -eq 0 ]; then
            print_success "Frontend dependencies installed"
        else
            print_warning "npm install failed"
        fi
    else
        print_warning "package.json not found in $VIZ_UI_PATH"
    fi

    cd - > /dev/null
}

# Generate environment setup script
generate_env_script() {
    print_header "Generating Environment Setup Script"

    ENV_SCRIPT="$HOME/.cml_env.sh"
    cat > "$ENV_SCRIPT" << 'EOF'
#!/bin/bash
# C-ML Environment Variables
# Source this file: source ~/.cml_env.sh

# MLIR/LLVM
if [ -d "$HOME/.local/llvm" ]; then
    export MLIR_DIR="$HOME/.local/llvm/lib/cmake/mlir"
    export LLVM_DIR="$HOME/.local/llvm/lib/cmake/llvm"
    export PATH="$HOME/.local/llvm/bin:$PATH"
    export LD_LIBRARY_PATH="$HOME/.local/llvm/lib:$LD_LIBRARY_PATH"
fi

# CUDA
if [ -d "/usr/local/cuda" ]; then
    export PATH="/usr/local/cuda/bin:$PATH"
    export LD_LIBRARY_PATH="/usr/local/cuda/lib64:$LD_LIBRARY_PATH"
fi

# Vulkan
if [ -d "/opt/vulkan" ]; then
    export VULKAN_SDK="/opt/vulkan"
    export PATH="$VULKAN_SDK/bin:$PATH"
    export LD_LIBRARY_PATH="$VULKAN_SDK/lib:$LD_LIBRARY_PATH"
    export VK_LAYER_PATH="$VULKAN_SDK/etc/vulkan/explicit_layer.d"
fi

# SLEEF
export LD_LIBRARY_PATH="$HOME/.local/lib:$LD_LIBRARY_PATH"
export PKG_CONFIG_PATH="$HOME/.local/lib/pkgconfig:$PKG_CONFIG_PATH"

# ROCm
if [ -d "/opt/rocm" ]; then
    export PATH="/opt/rocm/bin:$PATH"
    export LD_LIBRARY_PATH="/opt/rocm/lib:$LD_LIBRARY_PATH"
fi

# Rust/Cargo (for naga)
if [ -d "$HOME/.cargo" ]; then
    export PATH="$HOME/.cargo/bin:$PATH"
fi
EOF

    chmod +x "$ENV_SCRIPT"
    print_success "Environment script created: $ENV_SCRIPT"
    print_info "Add to your ~/.bashrc or ~/.zshrc:"
    echo "source ~/.cml_env.sh"
}

# Main installation function
main() {
    print_header "C-ML Development Environment Setup"

    detect_os
    print_info "Detected OS: $OS ($OS_FAMILY)"

    if [ "$OS" = "unknown" ]; then
        print_error "Unsupported operating system: $OSTYPE"
        exit 1
    fi

    detect_gpu
    print_info "GPU Type: $GPU_TYPE"

    # Ask user what to install
    echo ""
    print_info "What would you like to install?"
    echo "1) Everything (recommended)"
    echo "2) MLIR only (required)"
    echo "3) MLIR + CUDA"
    echo "4) MLIR + Vulkan"
    echo "5) MLIR + SLEEF"
    echo "6) MLIR + Codegen Tools (SPIRV, Metal, WGSL)"
    echo "7) Custom selection"
    echo ""
    read -p "Enter choice [1-7]: " choice

    case $choice in
        1)
            install_build_tools
            install_nodejs
            install_mlir
            install_cuda
            install_vulkan
            install_sleef
            install_blas
            install_rocm
            install_codegen_tools
            install_frontend_deps
            ;;
        2)
            install_build_tools
            install_mlir
            ;;
        3)
            install_build_tools
            install_mlir
            install_cuda
            ;;
        4)
            install_build_tools
            install_mlir
            install_vulkan
            ;;
        5)
            install_build_tools
            install_mlir
            install_sleef
            ;;
        6)
            install_build_tools
            install_mlir
            install_codegen_tools
            ;;
        7)
            install_build_tools
            [ "$(read -p 'Install Node.js/npm? [y/N]: ' ans; echo $ans)" = "y" ] && install_nodejs
            [ "$(read -p 'Install MLIR? [y/N]: ' ans; echo $ans)" = "y" ] && install_mlir
            [ "$(read -p 'Install CUDA? [y/N]: ' ans; echo $ans)" = "y" ] && install_cuda
            [ "$(read -p 'Install Vulkan? [y/N]: ' ans; echo $ans)" = "y" ] && install_vulkan
            [ "$(read -p 'Install SLEEF? [y/N]: ' ans; echo $ans)" = "y" ] && install_sleef
            [ "$(read -p 'Install BLAS? [y/N]: ' ans; echo $ans)" = "y" ] && install_blas
            [ "$(read -p 'Install ROCm? [y/N]: ' ans; echo $ans)" = "y" ] && install_rocm
            [ "$(read -p 'Install Codegen Tools (SPIRV, Metal, WGSL)? [y/N]: ' ans; echo $ans)" = "y" ] && install_codegen_tools
            [ "$(read -p 'Install Frontend Dependencies (React)? [y/N]: ' ans; echo $ans)" = "y" ] && install_frontend_deps
            ;;
        *)
            print_error "Invalid choice"
            exit 1
            ;;
    esac

    generate_env_script

    # Verify optional codegen tools
    print_header "Verifying Optional Codegen Tools"
    if command_exists spirv-as; then
        print_success "spirv-as found: $(which spirv-as)"
    else
        print_info "spirv-as not found (optional, for SPIR-V generation)"
    fi

    if command_exists spirv-cross; then
        print_success "spirv-cross found: $(which spirv-cross)"
    else
        print_info "spirv-cross not found (optional, for Metal codegen)"
    fi

    if command_exists llvm-spirv; then
        print_success "llvm-spirv found: $(which llvm-spirv)"
    else
        print_info "llvm-spirv not found (optional, for SPIR-V via LLVM)"
    fi

    if command_exists naga; then
        print_success "naga found: $(which naga)"
    else
        print_info "naga not found (optional, for WGSL codegen)"
    fi

    if command_exists tint; then
        print_success "tint found: $(which tint)"
    else
        print_info "tint not found (optional, alternative WGSL converter)"
    fi

    print_header "Installation Complete!"
    print_success "C-ML development environment is ready"
    print_info "Installed tools summary:"
    echo "  ✓ Build tools: gcc/clang, make, cmake, git"
    if command_exists python3; then
        echo "  ✓ Python3: $(python3 --version 2>/dev/null | head -n1)"
    elif command_exists python; then
        echo "  ✓ Python: $(python --version 2>/dev/null | head -n1)"
    fi
    if command_exists npm; then
        echo "  ✓ Node.js: $(node --version 2>/dev/null || echo 'unknown')"
        echo "  ✓ npm: v$(npm --version 2>/dev/null || echo 'unknown')"
    fi
    if command_exists mlir-opt; then
        echo "  ✓ MLIR tools: mlir-opt, mlir-translate, llc"
    fi
    echo ""
    print_info "Next steps:"
    echo "  1. Source the environment: source ~/.cml_env.sh"
    echo "  2. Build C-ML: cd /path/to/C-ML && mkdir build && cd build"
    echo "  3. Configure: cmake .. -DMLIR_DIR=\$MLIR_DIR"
    echo "  4. Build: make -j\$(nproc)"
    if command_exists npm; then
        echo "  5. Build frontend (optional): cd viz-ui && npm install && npm run build"
    fi
}

# Run main function
main "$@"
