# C-ML Development Environment Setup Script (PowerShell)
# Installs MLIR, CUDA, Vulkan, SLEEF, and other dependencies for Windows
# This file is generated by AI, so it may not be perfect.


param(
    [switch]$All,
    [switch]$MLIR,
    [switch]$CUDA,
    [switch]$Vulkan,
    [switch]$SLEEF,
    [switch]$BLAS
)

$ErrorActionPreference = "Stop"

# Colors for output
function Write-Success { Write-Host "✓ $args" -ForegroundColor Green }
function Write-Error-Custom { Write-Host "✗ $args" -ForegroundColor Red }
function Write-Info { Write-Host "ℹ $args" -ForegroundColor Blue }
function Write-Warning-Custom { Write-Host "⚠ $args" -ForegroundColor Yellow }
function Write-Header { Write-Host "`n=== $args ===" -ForegroundColor Cyan }

# Check if running as administrator
function Test-Administrator {
    $currentUser = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($currentUser)
    return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

# Detect GPU
function Detect-GPU {
    Write-Header "Detecting GPU"

    try {
        $gpu = Get-WmiObject Win32_VideoController | Where-Object { $_.Name -like "*NVIDIA*" }
        if ($gpu) {
            Write-Success "NVIDIA GPU detected: $($gpu.Name)"
            return "nvidia"
        }

        $gpu = Get-WmiObject Win32_VideoController | Where-Object { $_.Name -like "*AMD*" -or $_.Name -like "*Radeon*" }
        if ($gpu) {
            Write-Success "AMD GPU detected: $($gpu.Name)"
            return "amd"
        }

        Write-Info "No dedicated GPU detected or detection failed"
        return "none"
    } catch {
        Write-Warning-Custom "GPU detection failed: $_"
        return "none"
    }
}

# Install Chocolatey (if not installed)
function Install-Chocolatey {
    if (Get-Command choco -ErrorAction SilentlyContinue) {
        Write-Success "Chocolatey already installed"
        return
    }

    Write-Info "Installing Chocolatey package manager..."
    if (-not (Test-Administrator)) {
        Write-Error-Custom "Administrator privileges required to install Chocolatey"
        Write-Info "Run PowerShell as Administrator and try again"
        exit 1
    }

    Set-ExecutionPolicy Bypass -Scope Process -Force
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
    iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    Write-Success "Chocolatey installed"
}

# Install MLIR/LLVM
function Install-MLIR {
    Write-Header "Installing MLIR/LLVM"

    if (Get-Command clang -ErrorAction SilentlyContinue) {
        $version = clang --version | Select-String "version" | ForEach-Object { $_.Line }
        Write-Success "LLVM/Clang already installed: $version"
        return
    }

    if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
        Install-Chocolatey
    }

    Write-Info "Installing LLVM via Chocolatey..."
    choco install llvm -y

    # Set environment variables
    $llvmPath = "C:\Program Files\LLVM"
    if (Test-Path $llvmPath) {
        $env:Path = "$llvmPath\bin;$env:Path"
        $env:LLVM_DIR = "$llvmPath\lib\cmake\llvm"
        $env:MLIR_DIR = "$llvmPath\lib\cmake\mlir"

        Write-Success "MLIR installed"
        Write-Info "Add to your environment variables:"
        Write-Host "  LLVM_DIR=$llvmPath\lib\cmake\llvm"
        Write-Host "  MLIR_DIR=$llvmPath\lib\cmake\mlir"
        Write-Host "  Add $llvmPath\bin to PATH"
    } else {
        Write-Warning-Custom "LLVM installation path not found. Manual installation may be required."
        Write-Info "Download from: https://github.com/llvm/llvm-project/releases"
    }
}

# Install CUDA
function Install-CUDA {
    $gpuType = Detect-GPU
    if ($gpuType -ne "nvidia") {
        Write-Info "Skipping CUDA (no NVIDIA GPU detected)"
        return
    }

    Write-Header "Installing CUDA Toolkit"

    if (Get-Command nvcc -ErrorAction SilentlyContinue) {
        $version = nvcc --version | Select-String "release" | ForEach-Object { $_.Matches[0].Value }
        Write-Success "CUDA already installed: $version"
        return
    }

    if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
        Install-Chocolatey
    }

    Write-Info "Installing CUDA Toolkit via Chocolatey..."
    Write-Warning-Custom "This will install CUDA 12.x. For other versions, visit: https://developer.nvidia.com/cuda-downloads"

    choco install cuda -y

    Write-Success "CUDA installed"
    Write-Info "Add to your environment variables:"
    Write-Host "  Add C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.x\bin to PATH"
    Write-Host "  Add C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.x\lib\x64 to PATH"
}

# Install Vulkan SDK
function Install-Vulkan {
    Write-Header "Installing Vulkan SDK"

    if (Get-Command vulkaninfo -ErrorAction SilentlyContinue) {
        Write-Success "Vulkan SDK already installed"
        return
    }

    if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
        Install-Chocolatey
    }

    Write-Info "Installing Vulkan SDK via Chocolatey..."
    choco install vulkan-sdk -y

    Write-Success "Vulkan SDK installed"
    Write-Info "Vulkan SDK is typically installed to: C:\VulkanSDK\<version>"
    Write-Info "Add to your environment variables:"
    Write-Host "  VULKAN_SDK=C:\VulkanSDK\<version>"
    Write-Host "  Add %VULKAN_SDK%\Bin to PATH"
}

# Install SLEEF
function Install-SLEEF {
    Write-Header "Installing SLEEF"

    Write-Info "SLEEF installation on Windows requires building from source"
    Write-Info "Prerequisites:"
    Write-Host "  1. Install CMake"
    Write-Host "  2. Install Git"
    Write-Host "  3. Install Visual Studio with C++ development tools"
    Write-Host ""
    Write-Info "Build instructions:"
    Write-Host "  git clone https://github.com/shibatch/sleef.git"
    Write-Host "  cd sleef"
    Write-Host "  mkdir build && cd build"
    Write-Host "  cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%USERPROFILE%\.local .."
    Write-Host "  cmake --build . --config Release"
    Write-Host "  cmake --install ."

    Write-Warning-Custom "SLEEF must be built manually on Windows"
}

# Install BLAS
function Install-BLAS {
    Write-Header "Installing BLAS Libraries"

    if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
        Install-Chocolatey
    }

    Write-Info "Installing OpenBLAS via Chocolatey..."
    choco install openblas -y

    Write-Success "OpenBLAS installed"
}

# Install build tools
function Install-BuildTools {
    Write-Header "Installing Build Tools"

    if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
        Install-Chocolatey
    }

    $tools = @("cmake", "git", "python3", "ninja")
    foreach ($tool in $tools) {
        if (-not (Get-Command $tool -ErrorAction SilentlyContinue)) {
            Write-Info "Installing $tool..."
            choco install $tool -y
        } else {
            Write-Success "$tool already installed"
        }
    }

    # Check for Visual Studio
    $vsPath = "C:\Program Files\Microsoft Visual Studio"
    if (Test-Path $vsPath) {
        Write-Success "Visual Studio found"
    } else {
        Write-Warning-Custom "Visual Studio not found. Install Visual Studio 2019 or later with C++ tools"
        Write-Info "Download from: https://visualstudio.microsoft.com/"
    }
}

# Generate environment setup script
function Generate-EnvScript {
    Write-Header "Generating Environment Setup Script"

    $envScript = "$env:USERPROFILE\.cml_env.ps1"
    @"
# C-ML Environment Variables (PowerShell)
# Source this file: . `$PROFILE or add to your PowerShell profile

# MLIR/LLVM
if (Test-Path "C:\Program Files\LLVM") {
    `$env:LLVM_DIR = "C:\Program Files\LLVM\lib\cmake\llvm"
    `$env:MLIR_DIR = "C:\Program Files\LLVM\lib\cmake\mlir"
    `$env:Path = "C:\Program Files\LLVM\bin;" + `$env:Path
}

# CUDA
if (Test-Path "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA") {
    `$cudaPath = (Get-ChildItem "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA" | Sort-Object Name -Descending | Select-Object -First 1).FullName
    `$env:Path = "`$cudaPath\bin;" + `$env:Path
    `$env:Path = "`$cudaPath\lib\x64;" + `$env:Path
}

# Vulkan
if (Test-Path "C:\VulkanSDK") {
    `$vulkanPath = (Get-ChildItem "C:\VulkanSDK" | Sort-Object Name -Descending | Select-Object -First 1).FullName
    `$env:VULKAN_SDK = `$vulkanPath
    `$env:Path = "`$vulkanPath\Bin;" + `$env:Path
}

# SLEEF (if installed to user directory)
if (Test-Path "`$env:USERPROFILE\.local\lib") {
    `$env:Path = "`$env:USERPROFILE\.local\bin;" + `$env:Path
}
"@ | Out-File -FilePath $envScript -Encoding UTF8

    Write-Success "Environment script created: $envScript"
    Write-Info "Add to your PowerShell profile:"
    Write-Host "  . $envScript"
}

# Main installation function
function Main {
    Write-Header "C-ML Development Environment Setup (Windows)"

    $gpuType = Detect-GPU

    if ($All) {
        Install-BuildTools
        Install-MLIR
        Install-CUDA
        Install-Vulkan
        Install-SLEEF
        Install-BLAS
    } elseif ($MLIR) {
        Install-BuildTools
        Install-MLIR
    } elseif ($CUDA) {
        Install-BuildTools
        Install-MLIR
        Install-CUDA
    } elseif ($Vulkan) {
        Install-BuildTools
        Install-MLIR
        Install-Vulkan
    } elseif ($SLEEF) {
        Install-BuildTools
        Install-MLIR
        Install-SLEEF
    } else {
        Write-Info "What would you like to install?"
        Write-Host "Usage: .\setup_env.ps1 [-All] [-MLIR] [-CUDA] [-Vulkan] [-SLEEF] [-BLAS]"
        Write-Host ""
        Write-Host "Examples:"
        Write-Host "  .\setup_env.ps1 -All          # Install everything"
        Write-Host "  .\setup_env.ps1 -MLIR          # Install MLIR only"
        Write-Host "  .\setup_env.ps1 -MLIR -CUDA    # Install MLIR + CUDA"
        exit 0
    }
# This file is generated by AI, so it may not be perfect.

    Generate-EnvScript

    Write-Header "Installation Complete!"
    Write-Success "C-ML development environment is ready"
    Write-Info "Next steps:"
    Write-Host "  1. Source the environment: . ~\.cml_env.ps1"
    Write-Host "  2. Build C-ML: cd C-ML && mkdir build && cd build"
    Write-Host "  3. Configure: cmake .. -DMLIR_DIR=`$env:MLIR_DIR"
    Write-Host "  4. Build: cmake --build . --config Release"
}

# Run main function
Main
