#version 450
layout(local_size_x = 256) in;
layout(std430, binding = 0) readonly  buffer BufA { float a[]; };
layout(std430, binding = 1) writeonly buffer BufO { float o[]; };
layout(std430, binding = 2) readonly  buffer BufB { float b[]; };
layout(std430, binding = 3) readonly  buffer BufP { uint n; uint op; uint n0; uint n1; };
void main() {
    uint i = gl_GlobalInvocationID.x;
    if (i >= n) return;
    float x = a[i % n0];
    float y = b[i % n1];
    float r;
    if      (op == 0u) r = x + y;
    else if (op == 1u) r = x - y;
    else if (op == 2u) r = x * y;
    else if (op == 3u) r = x / y;
    else               r = max(x, y);
    o[i] = r;
}
